### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by r3pek** [jgeusebroek/docker-privatebin#2]
Any chance you can incorporate MySQL support?

```
#2 /privatebin/index.php(18): PrivateBin\PrivateBin->__construct()
#3 {main}
  thrown in /privatebin/lib/Configuration.php on line 168" while reading response header from upstream, client: 10.0.0.90, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "paste.xxxxxxx.xxxx"
2018/03/18 21:56:40 [error] 19#19: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'PDO' not found in /privatebin/lib/Configuration.php:168
Stack trace:
#0 /privatebin/lib/PrivateBin.php(182): PrivateBin\Configuration->__construct()
#1 /privatebin/lib/PrivateBin.php(131): PrivateBin\PrivateBin->_init()
#2 /privatebin/index.php(18): PrivateBin\PrivateBin->__construct()
```

**Comment by jgeusebroek** [comment]
Sure! https://github.com/jgeusebroek/docker-privatebin/commit/d8a9f45cb250ee2a0dda702583330f7634960033. Done.
